
apiVersion: v1
kind: Pod
metadata:
  name: firewall-pod
  namespace: llm-config
spec:
  containers:
  - name: container-name
    image: dokken/ubuntu-20.04
    command: ["sleep", "infinity"] # keep container alive
    resources:
      limits:
        memory: "2Gi"
        cpu: "2"
    env:
    - name: POD_NAMESPACE_DNS
      value: 10.99.30.112
